{\rtf1\ansi\ansicpg1252\cocoartf2708
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 .AppleSystemUIFontMonospaced-Regular;}
{\colortbl;\red255\green255\blue255;\red24\green26\blue30;\red255\green255\blue255;\red0\green0\blue0;
}
{\*\expandedcolortbl;;\cssrgb\c12157\c13725\c15686;\cssrgb\c100000\c100000\c100000;\cssrgb\c0\c0\c0;
}
\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs24 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 name: HARK_SSJ_example\cb1 \
\cb3 channels:\cb1 \
\cb3   - conda-forge\cb1 \
\cb3 dependencies:\cb1 \
\cb3   - python=3.9\cb1 \
  - scipy\
\cb3   - matplotlib\cb1 \
\cb3   - numpy\cb1 \
\cb3   - pip:\
\pard\pardeftab720\partightenfactor0
\cf0 \cb3 \strokec4 	\cf2 \cb3 \strokec2 - \cf0 \cb3 \strokec4 -r requirements.txt\cf2 \cb1 \strokec2 \
}